import react from '@vitejs/plugin-react'
import {configDefaults, defineConfig} from 'vitest/config'

export default defineConfig({
  plugins: [react()],
  resolve: {
    tsconfigPaths: true,
  },
  test: {
    coverage: {
      exclude: [
        '**/*.test.ts',
        '**/*.test.tsx',
        '**/configured-*.ts',
        '**/database-*.ts',
        '**/ui-user.ts',
        'src/server/database/**',
      ],
      include: [
        'i18n.ts',
        'src/app/api/**/route.ts',
        'src/app/[locale]/dashboard/(protected)/editorial-actions.ts',
        'src/app/[locale]/dashboard/(protected)/inquiries/inquiry-actions.ts',
        'src/components/admin/*.tsx',
        'src/components/consent/**/*.{ts,tsx}',
        'src/components/editorial/*.tsx',
        'src/components/forms/feedback-form.tsx',
        'src/components/lib/google-tag-manager.tsx',
        'src/components/molecules/newsletter-cta.tsx',
        'src/components/seo/*.tsx',
        'src/components/studio/*.tsx',
        'src/lib/localized-path.ts',
        'src/server/admin/admin-service.ts',
        'src/server/auth/**/*.ts',
        'src/server/contact/public-contact.ts',
        'src/server/email/**/*.ts',
        'src/server/editorial-content/**/*.ts',
        'src/server/editorial-persistence/**/*.ts',
        'src/server/editorial-publishing/**/*.ts',
        'src/server/inquiries/**/*.ts',
        'src/server/operations/**/*.ts',
        'src/server/security/**/*.ts',
        'src/server/storage/**/*.ts',
        'src/server/studio-auth/**/*.ts',
        'src/server/studio-content/**/*.ts',
        'src/server/studio-inquiries/**/*.ts',
        'src/server/studio-operations/**/*.ts',
        'src/utils/prepare-metadata.ts',
        'scripts/lib/v2-demo-seed.mjs',
        'scripts/seed-v2-demo.mjs',
      ],
      provider: 'v8',
      reporter: ['text', 'html'],
      thresholds: {
        branches: 80,
        functions: 80,
        lines: 80,
        statements: 80,
      },
    },
    environment: 'jsdom',
    exclude: [...configDefaults.exclude],
    globals: true,
    include: [
      'prisma/**/*.test.ts',
      'scripts/**/*.test.mjs',
      'src/**/*.test.ts',
      'src/**/*.test.tsx',
    ],
    setupFiles: ['./src/test/setup.ts'],
  },
})
